name: create issue branch

on:
  issues:
    types:
      - opened
      
jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_REPO: ${{ github.repository }}
    steps:
      - name: print issue number
        run: echo $ISSUE_NUMBER  
      - name: create branch
        run: git checkout feat/be/#$ISSUE_NUMBER
