name: create issue branch

on:
  issues:
    types:
      - opened
      
jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      
    steps:
      - name: print issue number
        run: echo $ISSUE_NUMBER  
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        with:
          branch: refs/heads/long/branch/name
          sha: '${{ github.event.pull_request.head.sha }}'
